version: 0.2

env:
  parameter-store:
    GOOGLEMAP_API_KEY: "GOOGLEMAP_API_KEY"

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp ./dist s3://${TARGET_BUCKET} --recursive --force