version: 0.2

env:
  parameter-store:
    GOOGLEMAP_API_KEY: "GOOGLEMAP_API_KEY"

phases:
  install:
    - npm install
  build:
    - npm run build
  post-build:
    - cwd=`dirname "$0"`
    - aws s3 cp ${cwd}/dist s3://${BUCKET_NAME} --recursive --force
    